#!/bin/bash

echo "🎬 BV Studios - Video Upload Guide"
echo "=================================="
echo ""
echo "To add your real videos to the portfolio:"
echo ""
echo "1. 📁 Create video directories:"
echo "   mkdir -p public/media/videos/weddings"
echo "   mkdir -p public/media/videos/commercial"
echo "   mkdir -p public/media/videos/events"
echo ""
echo "2. 🎥 Upload your videos:"
echo "   - Copy your video files to the appropriate directories"
echo "   - Supported formats: .mp4, .mov, .avi"
echo "   - Recommended size: 1920x1080 or 1280x720"
echo ""
echo "3. 🔗 Update video URLs in components/Portfolio.js:"
echo "   - Replace placeholder YouTube URLs with your actual video URLs"
echo "   - Or upload to YouTube/Vimeo and use embed URLs"
echo ""
echo "4. 🖼️ Add video thumbnails:"
echo "   - Create thumbnails for each video"
echo "   - Save as .jpg or .png in public/media/images/portfolio/"
echo ""
echo "5. 📝 Update portfolio items:"
echo "   - Edit the portfolioItems array in components/Portfolio.js"
echo "   - Add your actual video titles and descriptions"
echo ""
echo "Example video URL formats:"
echo "  - YouTube: https://www.youtube.com/embed/YOUR_VIDEO_ID"
echo "  - Vimeo: https://player.vimeo.com/video/YOUR_VIDEO_ID"
echo "  - Local: /media/videos/weddings/your-video.mp4"
echo ""
echo "Need help? Check the README.md for detailed instructions." 